questions:
  "2 + 2 = ?": "4"
  "Ibukota Indonesia?": "jakarta"
  "Minecraft dibuat oleh siapa?": "notch"
  "Hewan apa yang suka wortel?": "kelinci"
  "Siapa Nama Pembuat Server?": "radianza"
  "98 + 72 = ?": "170"
  "Apa sila ke 3?": "persatuan indonesia"
  "Habis mandi kuterus?": "tidur"
  "Malam pasti?": "gelap"
  "Warna favorit Owner?": "biru"